name: ZAP DAST scan

on:
  workflow_dispatch:   # Manual trigger
          
jobs:
   zap-baseline:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4
         
       - name: ZAP Baseline Scan
         uses: zaproxy/action-baseline@0.7.0
         with:
            target: http://testfire.net
            cmd_options: "a"
            rules_file_name: .zap/rules.tsy
            allow_issue_writing: false
      
    
